spring:
  application:
    name: travian-service
  jmx:
    default-domain: travian-service
internet:
  proxy:
    enable: false
    host: east.network.fedex.com
    port: 3128
logging:
  level:
    root: WARN
    com:
      travian: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate: WARN
      apache:
        commons:
          dbcp2: ERROR
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n [%X{X-B3-TraceId:-}]'
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n [%X{X-B3-TraceId:-}]'
  file: /usr/local/log/travian-service.log⁩